name: Derius-Mining
version: 0.1_dev
main: dk.muj.derius.mining.DeriusMining
#website: http://muj.dk/Derius/Mining
authors: [madus, ulumulu1510]
description: §eDerius mining
depend: [Derius-Core]
load: startup
