name: Derius-Mining
version: 0.1_dev
main: dk.muj.derius.mining.DeriusMining
#website: http://muj.dk/Derius/Mining
authors: [Madus, Ulumulu1510]
description: <g>Derius Mining is a mining skill for the Derius skill framework.
depend: [Derius-Core]
load: startup
